version: '3.9'

services:
  # database
  db:
    container_name: shop_database
    image: postgres:14.5
    env_file:
      - ./.env
    restart: always
    healthcheck:
      test: pg_isready -q --username=$$POSTGRES_USER --dbname=$$POSTGRES_NAME
      timeout: 45s
      interval: 10s
      retries: 10
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - postgres_socket:/var/run/postgresql/

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: shop_project_rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_log:/var/log/rabbitmq
    env_file:
      - ./.env
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
      #networks:
      #      - rabbitmq_shop_net

  redis:
    container_name: shop_project_redis
    image: redis:latest
    restart: always
    healthcheck:
      test: redis-cli ping
      timeout: 45s
      interval: 10s
      retries: 10

  celery:
    container_name: shop_project_celery_worker
    build:
      dockerfile: dockerfiles/Dockerfile
      context: .
    command: worker
    env_file:
      - ./.env

  shop:
    container_name: shop_project_django
    build:
      dockerfile: dockerfiles/Dockerfile
      context: .
    command: server
    stdin_open: true
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./:/code
    depends_on:
      shop_project_redis:
        condition: service_healthy
      shop_project_rabbitmq:
        condition: service_healthy



  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - ./:/app
    ports:
      - "84:84"
    env_file:
      - ./.env

volumes:
  rabbitmq_data:
  rabbitmq_log:
  postgres_data:
  postgres_socket:
